const ShopTypes = {
  FETCH_COLLECTION_REQUEST : 'FETCH_COLLECTION_REQUESTS',
  FETCH_COLLECTION_SUCCESS : 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE : 'FETCH_COLLECTION_FAILURE'
}
export default ShopTypes;